# Generated by Django 4.1.3 on 2022-11-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='author',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='age_gte_18'),
        ),
    ]
